### ISSUE TITLE
charakterziffer.github.io likes to take part in 2024

### ISSUE THREAD

**Issue by charakterziffer** [css-naked-day/css-naked-day.github.io#113]
Hi, I’d like to strip my blog https://charakterziffer.github.io/ around April 9, 2024. Would you kindly add me to the list at https://css-naked-day.github.io/2024.html ?
(My real life name is *Gerhard Großmann*, but I prefer to be linked as *charakterziffer*)

**Comment by arkhi** [comment]
Sure! We can it on the 9th!

**Comment by charakterziffer** [comment]
Update: The CSS of my blog is deactivated now and will stay so for at least the next 60 hours. Tomorrow I’ll publish an explaining article (in addition to the small note that’s on top of each page at the moment).

**Comment by j9t** [comment]
Hi @charakterziffer—cheers for participating in CSS Naked Day!

Just to make sure—I don’t know if @arkhi and you have a different agreement, but I’d recommend to create a pull request to add yourself to the list. While the number of participants is still manageable, it doesn’t normally scale for Fabien and me to add people manually. Thanks!

**Comment by charakterziffer** [comment]
I hope I did everything right for the pull request. Thanks!

**Comment by arkhi** [comment]
@j9t & @charakterziffer: I originally thought of doing it myself but the PR was more than welcome. Thanks to you both.
