### ISSUE TITLE
css-naked-day.github.io is styled on April 9th

### ISSUE THREAD

**Issue by decibyte** [css-naked-day/css-naked-day.github.io#137]
I think it's fair to expect the CSS Naked Day website to be naked on CSS Naked Day.

![image](https://github.com/css-naked-day/css-naked-day.github.io/assets/224219/85bbe8c7-a7db-45fc-aaea-ae2302a85a9d)

**Comment by arkhi** [comment]
Agreed! PR are always welcome. :)

**Comment by j9t** [comment]
I can prepare something quick (unless either of you is already on it).

**Comment by j9t** [comment]
Prepared with #139.

**Comment by decibyte** [comment]
Nice, @j9t :)

**Comment by j9t** [comment]
(Undo prepared with #140.)
